name : Code Coverage Check

on: 
  push:
    branches:
    - main
    - HW*
  pull_request:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: 3.7

    - name: Install dependencies and library
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install gymnasium
        pip install -e SevenWondersEnv
    - name: Generate Report
      run: |
        cd SevenWondersEnv/SevenWonEnv/envs/
        python -m pip install --upgrade pip
        pip install coverage
        coverage run -m unittest Test/allTests.py 
        coverage report
        coverage json
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3


